### ISSUE TITLE
 Cottages anvil is no good. Take it out.

### ISSUE THREAD

**Issue by Andarius68** [Cianaodh-Media/Beul-aithris#3]
Chop chop! It's no good. Or figure out how it works and tell everybody.

**Comment by MCLV-pandorabox** [comment]
I second this motion :D

**Comment by Andarius68** [comment]
I believe this issue has been resolved (or will be at the next restart) with the upgrading to the fluxionary fork minetest-cottages which additionally adds the ability to swap tools without having to switch hands. Note, this version of the anvil can only be picked up by mining it with the blacksmith's hammer. Trying to do so with a pickaxe doesn't work.
